In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import dataframe_image as dfi

In [2]:
data = pd.read_csv('C:\\Users\\roadr\\GaTech\\Popular_Baby_Names.csv')

In [3]:
data.head()
data["Child's First Name"] = data["Child's First Name"].str.upper()

In [4]:
data['Ethnicity'] = data['Ethnicity'].replace({
    'ASIAN AND PACI': 'ASIAN AND PACIFIC ISLANDER',
    'BLACK NON HISP': 'BLACK NON HISPANIC',
    'WHITE NON HISP': 'WHITE NON HISPANIC'
})

In [5]:
# Group the data by Ethnicity and Child's First Name, summing up the counts
aggregated_counts = data.groupby(['Ethnicity', "Child's First Name"])['Count'].sum().reset_index()

# Rename columns for clarity
aggregated_counts.columns = ['Ethnicity', "Child's First Name", 'Total Count']

# Sort the data for better readability
aggregated_counts = aggregated_counts.sort_values(by=['Ethnicity', 'Total Count'], ascending=[True, False])

In [6]:
aggregated_counts

                       Ethnicity Child's First Name  Total Count
226   ASIAN AND PACIFIC ISLANDER              ETHAN         5677
310   ASIAN AND PACIFIC ISLANDER             JAYDEN         5581
511   ASIAN AND PACIFIC ISLANDER               RYAN         5214
404   ASIAN AND PACIFIC ISLANDER              LUCAS         4356
156   ASIAN AND PACIFIC ISLANDER              CHLOE         4099
...                          ...                ...          ...
3288          WHITE NON HISPANIC            VIVIANA           10
3290          WHITE NON HISPANIC             WALKER           10
3347          WHITE NON HISPANIC             ZAINAB           10
3348          WHITE NON HISPANIC            ZAKARIA           10
3350          WHITE NON HISPANIC               ZANE           10

[3358 rows x 3 columns]

In [7]:
# Calculate the total count for each ethnicity
ethnicity_total_counts = aggregated_counts.groupby('Ethnicity')['Total Count'].sum().reset_index()
ethnicity_total_counts.columns = ['Ethnicity', 'Ethnicity Total Count']

# Merge the total counts back into the most_popular_names dataframe
most_popular_names = most_popular_names.merge(ethnicity_total_counts, on='Ethnicity')

# Calculate the percentage for each ethnicity
total_count_all = ethnicity_total_counts['Ethnicity Total Count'].sum()
most_popular_names['Percentage of Total'] = (most_popular_names['Ethnicity Total Count'] / total_count_all) * 100

# Drop the ethnicity total count column for cleaner presentation
most_popular_names = most_popular_names.drop(columns=['Ethnicity Total Count'])

NameError: name 'most_popular_names' is not defined

In [ ]:
most_popular_names

In [8]:
dfi.export(most_popular_names, 'descriptive.png')

NameError: name 'most_popular_names' is not defined

In [9]:
# Group the data by year, ethnicity, and name to calculate the total count for each combination
yearly_counts = data.groupby(['Year of Birth', 'Ethnicity', "Child's First Name"])['Count'].sum().reset_index()

# Calculate the total count for each year and ethnicity
total_count_by_year_ethnicity = yearly_counts.groupby(['Year of Birth', 'Ethnicity'])['Count'].sum().reset_index()
total_count_by_year_ethnicity.columns = ['Year of Birth', 'Ethnicity', 'Total Count']

# Find the most popular and least popular names for each year and ethnicity
most_popular_names_by_year = yearly_counts.loc[yearly_counts.groupby(['Year of Birth', 'Ethnicity'])['Count'].idxmax()]
least_popular_names_by_year = yearly_counts.loc[yearly_counts.groupby(['Year of Birth', 'Ethnicity'])['Count'].idxmin()]

# Merge the most popular, least popular, and total count data
most_popular_names_by_year = most_popular_names_by_year.rename(columns={
    "Child's First Name": "Most Popular Name",
    "Count": "Most Popular Count"
})
least_popular_names_by_year = least_popular_names_by_year.rename(columns={
    "Child's First Name": "Least Popular Name",
    "Count": "Least Popular Count"
})

# Merge the datasets
summary_by_year_ethnicity = total_count_by_year_ethnicity.merge(
    most_popular_names_by_year[['Year of Birth', 'Ethnicity', 'Most Popular Name', 'Most Popular Count']],
    on=['Year of Birth', 'Ethnicity']
).merge(
    least_popular_names_by_year[['Year of Birth', 'Ethnicity', 'Least Popular Name', 'Least Popular Count']],
    on=['Year of Birth', 'Ethnicity']
)

In [10]:
summary_by_year_ethnicity

,Year of Birth,Ethnicity,Total Count,Most Popular Name,Most Popular Count,Least Popular Name,Least Popular Count
0,2011,ASIAN AND PACIFIC ISLANDER,56406,ETHAN,1239,AIZA,70
1,2011,BLACK NON HISPANIC,73668,JAYDEN,1288,NATALIE,66
2,2011,HISPANIC,170069,JAYDEN,2556,CHRISTINA,66
3,2011,WHITE NON HISPANIC,173458,MICHAEL,2044,ANGELICA,70
4,2012,ASIAN AND PACIFIC ISLANDER,70985,RYAN,1379,JULIA,60
5,2012,BLACK NON HISPANIC,70050,ETHAN,1057,ABDOUL,70
6,2012,HISPANIC,161423,JAYDEN,2184,MARILYN,66
7,2012,WHITE NON HISPANIC,183854,JOSEPH,2100,TOMAS,60
8,2013,ASIAN AND PACIFIC ISLANDER,62639,JAYDEN,1320,ASHER,60
9,2013,BLACK NON HISPANIC,68980,AIDEN,931,JAMEL,66
10,2013,HISPANIC,155786,JAYDEN,2112,BRAYDEN,60
11,2013,WHITE NON HISPANIC,183313,DAVID,2128,DAISY,60
12,2014,ASIAN AND PACIFIC ISLANDER,66038,JAYDEN,1122,AAYAN,60
13,2014,BLACK NON HISPANIC,67599,NOAH,896,DEVIN,60
14,2014,HISPANIC,154094,LIAM,2184,DENNIS,60
15,2014,WHITE NON HISPANIC,185986,JOSEPH,1800,ADRIANNA,70
16,2015,ASIAN AND PACIFIC ISLANDER,9584,JAYDEN,190,AARYAN,10
17,2015,BLACK NON HISPANIC,9637,NOAH,163,ABDOUL,10
18,2015,HISPANIC,22813,LIAM,356,ALANI,10
19,2015,WHITE NON HISPANIC,27566,DAVID,299,ADELINA,10
20,2016,ASIAN AND PACIFIC ISLANDER,9973,ETHAN,193,AILEEN,10
21,2016,BLACK NON HISPANIC,9147,NOAH,148,ABRAHAM,10
22,2016,HISPANIC,22086,LIAM,387,ADELINE,10
23,2016,WHITE NON HISPANIC,27534,JOSEPH,261,ANA,10
24,2017,ASIAN AND PACIFIC ISLANDER,8865,MUHAMMAD,157,AALIYAH,10
25,2017,BLACK NON HISPANIC,8699,NOAH,148,ABDOUL,10
26,2017,HISPANIC,20701,LIAM,407,ABBY,10
27,2017,WHITE NON HISPANIC,27130,DAVID,282,ALISA,10
28,2018,ASIAN AND PACIFIC ISLANDER,8068,MUHAMMAD,164,AAHIL,10
29,2018,BLACK NON HISPANIC,8176,NOAH,161,ANDRE,10
30,2018,HISPANIC,19840,LIAM,399,ADELYN,10
31,2018,WHITE NON HISPANIC,27230,DAVID,274,ABDULLAH,10
32,2019,ASIAN AND PACIFIC ISLANDER,8065,ETHAN,154,AAHIL,10
33,2019,BLACK NON HISPANIC,7664,NOAH,135,AHMED,10
34,2019,HISPANIC,18398,LIAM,423,ABBY,10
35,2019,WHITE NON HISPANIC,26569,DAVID,252,ALIYA,10
36,2020,ASIAN AND PACIFIC ISLANDER,6158,ETHAN,136,ABRAR,10
37,2020,BLACK NON HISPANIC,6593,NOAH,118,AHMED,10
38,2020,HISPANIC,16852,LIAM,374,ADELINE,10
39,2020,WHITE NON HISPANIC,23706,JOSEPH,232,ALIZA,10
40,2021,ASIAN AND PACIFIC ISLANDER,5482,MUHAMMAD,138,AARIZ,10
41,2021,BLACK NON HISPANIC,6158,NOAH,119,AMOURA,10
42,2021,HISPANIC,16963,LIAM,446,ADELE,10
43,2021,WHITE NON HISPANIC,24000,MOSHE,240,ADELAIDE,10

In [17]:
group_gender_name = (data.groupby(['Gender', "Child's First Name"], as_index=False).agg({'Count' : 'sum'}))
total_gender_name = group_gender_name.groupby('Gender')['Count'].sum()
group_gender_name['Percentage'] = group_gender_name.apply(lambda row: (row['Count'] / total_gender_name[row['Gender']]) * 100, axis = 1)

In [18]:
group_gender_name

      Gender Child's First Name  Count  Percentage
0     FEMALE            AALIYAH   4219    0.411378
1     FEMALE              AARYA     81    0.007898
2     FEMALE              AAYAT     10    0.000975
3     FEMALE               ABBY    589    0.057431
4     FEMALE            ABIGAIL   9400    0.916556
...      ...                ...    ...         ...
2054    MALE               ZAYN    257    0.019582
2055    MALE                ZEV   1729    0.131741
2056    MALE               ZION   2037    0.155209
2057    MALE              ZOHAN     20    0.001524
2058    MALE             ZYAIRE    140    0.010667

[2059 rows x 4 columns]

In [19]:
total_5count_male = group_gender_name[group_gender_name['Gender'] == 'MALE'].nlargest(5, 'Count').reset_index(drop = True)

In [20]:
total_5count_male

  Gender Child's First Name  Count  Percentage
0   MALE              ETHAN  22419    1.708209
1   MALE              JACOB  21614    1.646873
2   MALE             JAYDEN  21317    1.624243
3   MALE             DANIEL  18769    1.430099
4   MALE            MATTHEW  18121    1.380724

In [26]:
dfi.export(total_5count_male, "top5male.png")

In [23]:
total_5count_female = group_gender_name[group_gender_name['Gender'] == 'FEMALE'].nlargest(5, 'Count').reset_index(drop = True)
total_5count_female

   Gender Child's First Name  Count  Percentage
0  FEMALE             SOPHIA  18285    1.782897
1  FEMALE           ISABELLA  17677    1.723613
2  FEMALE               EMMA  16121    1.571894
3  FEMALE             OLIVIA  16004    1.560486
4  FEMALE                MIA  15224    1.484431

In [27]:
dfi.export(total_5count_female, "top5female.png")

In [28]:
most_male_bible = ['DAVID', 'MOSES', 'JACOB', 'SAUL', 'AARON', 'ABRAHAM', 'SOLOMON', 'JOSEPH', 'PAUL', 'JOSHUA']

In [29]:
most_female_bible = ['MARY', 'SALOME', 'SHELAZIOM', 'MARTHA', 'JOANNA', 'SAPPHIRA', 'BERNICE', 'IMMA', 'MARA', 'SARAH']

In [30]:
bible_names = ['DAVID', 'MOSES', 'JACOB', 'SAUL', 'AARON', 'ABRAHAM', 'SOLOMON', 'JOSEPH', 'PAUL', 'JOSHUA','MARY', 'SALOME', 'SHELAZIOM', 'MARTHA', 'JOANNA', 'SAPPHIRA', 'BERNICE', 'IMMA', 'MARA','SARAH']

---

In [54]:
data['is_Biblical'] = data["Child's First Name"].isin(bible_names)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21612 entries, 0 to 61140
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year of Birth       21612 non-null  int64
 1   Gender              21612 non-null  object
 2   Ethnicity           21612 non-null  object
 3   Child's First Name  21612 non-null  object
 4   Count               21612 non-null  int64
 5   Rank                21612 non-null  int64
 6   is_Biblical         21612 non-null  bool
dtypes: bool(1), int64(3), object(3)
memory usage: 1.2+ MB

C:\Users\roadr\AppData\Local\Temp\ipykernel_20720\3556553230.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['is_Biblical'] = data["Child's First Name"].isin(bible_names)

In [55]:
data = data.drop_duplicates()

In [61]:
data['Count'].sum()

712016

In [56]:
test2 = data.loc[data['is_Biblical']]
test2

,Year of Birth,Gender,Ethnicity,Child's First Name,Count,Rank,is_Biblical
166,2011,FEMALE,HISPANIC,SARAH,53,38,True
432,2011,FEMALE,WHITE NON HISPANIC,MARY,16,75,True
489,2011,FEMALE,WHITE NON HISPANIC,SARAH,177,6,True
548,2011,MALE,ASIAN AND PACIFIC ISLANDER,AARON,51,19,True
589,2011,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,28,38,True
617,2011,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,49,21,True
632,2011,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,21,45,True
633,2011,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,36,31,True
698,2011,MALE,BLACK NON HISPANIC,AARON,53,28,True
750,2011,MALE,BLACK NON HISPANIC,DAVID,84,15,True
782,2011,MALE,BLACK NON HISPANIC,JACOB,82,17,True
807,2011,MALE,BLACK NON HISPANIC,JOSEPH,35,39,True
808,2011,MALE,BLACK NON HISPANIC,JOSHUA,128,5,True
898,2011,MALE,HISPANIC,AARON,102,33,True
901,2011,MALE,HISPANIC,ABRAHAM,22,82,True
1038,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,38,13,True
1083,2011,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,38,13,True
1262,2011,FEMALE,BLACK NON HISPANIC,SARAH,40,15,True
1489,2011,MALE,HISPANIC,JACOB,303,3,True
1530,2011,MALE,HISPANIC,JOSEPH,140,22,True
1531,2011,MALE,HISPANIC,JOSHUA,190,11,True
1598,2011,MALE,HISPANIC,PAUL,16,88,True
1649,2011,MALE,WHITE NON HISPANIC,AARON,67,49,True
1650,2011,MALE,WHITE NON HISPANIC,ABRAHAM,172,12,True
1725,2011,MALE,WHITE NON HISPANIC,DAVID,258,4,True
1797,2011,MALE,WHITE NON HISPANIC,JOSEPH,281,2,True
1798,2011,MALE,WHITE NON HISPANIC,JOSHUA,89,37,True
1857,2011,MALE,WHITE NON HISPANIC,MOSES,31,76,True
1877,2011,MALE,WHITE NON HISPANIC,PAUL,26,81,True
1923,2011,MALE,WHITE NON HISPANIC,SOLOMON,48,60,True
3370,2011,MALE,HISPANIC,DAVID,178,15,True
3728,2011,MALE,WHITE NON HISPANIC,JACOB,265,3,True
4048,2012,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,37,19,True
4101,2012,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,47,12,True
4276,2012,FEMALE,BLACK NON HISPANIC,SARAH,29,29,True
4565,2012,FEMALE,HISPANIC,SALOME,10,79,True
4569,2012,FEMALE,HISPANIC,SARAH,43,46,True
4789,2012,FEMALE,WHITE NON HISPANIC,JOANNA,11,82,True
4857,2012,FEMALE,WHITE NON HISPANIC,MARY,23,70,True
4925,2012,FEMALE,WHITE NON HISPANIC,SARAH,209,3,True
4979,2012,MALE,ASIAN AND PACIFIC ISLANDER,AARON,66,19,True
5030,2012,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,40,33,True
5061,2012,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,48,27,True
5077,2012,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,29,42,True
5078,2012,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,45,29,True
5158,2012,MALE,BLACK NON HISPANIC,AARON,59,19,True
5212,2012,MALE,BLACK NON HISPANIC,DAVID,67,16,True
5235,2012,MALE,BLACK NON HISPANIC,JACOB,58,20,True
5254,2012,MALE,BLACK NON HISPANIC,JOSEPH,52,24,True
5255,2012,MALE,BLACK NON HISPANIC,JOSHUA,124,5,True
5313,2012,MALE,BLACK NON HISPANIC,PAUL,13,58,True
5340,2012,MALE,HISPANIC,AARON,126,28,True
5343,2012,MALE,HISPANIC,ABRAHAM,19,91,True
5413,2012,MALE,HISPANIC,DAVID,176,18,True
5475,2012,MALE,HISPANIC,JACOB,293,2,True
5511,2012,MALE,HISPANIC,JOSEPH,150,23,True
5512,2012,MALE,HISPANIC,JOSHUA,177,17,True
5582,2012,MALE,HISPANIC,PAUL,12,98,True
5604,2012,MALE,HISPANIC,SAUL,12,98,True
5630,2012,MALE,WHITE NON HISPANIC,AARON,95,32,True
5631,2012,MALE,WHITE NON HISPANIC,ABRAHAM,132,20,True
5704,2012,MALE,WHITE NON HISPANIC,DAVID,289,2,True
5776,2012,MALE,WHITE NON HISPANIC,JACOB,242,4,True
5791,2012,MALE,WHITE NON HISPANIC,JOSEPH,300,1,True
5792,2012,MALE,WHITE NON HISPANIC,JOSHUA,79,38,True
5849,2012,MALE,WHITE NON HISPANIC,MOSES,18,86,True
5872,2012,MALE,WHITE NON HISPANIC,PAUL,28,76,True
5920,2012,MALE,WHITE NON HISPANIC,SOLOMON,36,68,True
6109,2013,MALE,BLACK NON HISPANIC,DAVID,51,26,True
6255,2013,MALE,BLACK NON HISPANIC,JACOB,74,14,True
6309,2014,MALE,BLACK NON HISPANIC,ABRAHAM,13,57,True
6360,2014,MALE,HISPANIC,JOSEPH,114,25,True
6388,2013,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,32,20,True
6559,2013,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,43,13,True
6802,2013,MALE,WHITE NON HISPANIC,MOSES,31,79,True
6807,2013,MALE,ASIAN AND PACIFIC ISLANDER,AARON,66,13,True
6839,2014,MALE,HISPANIC,AARON,129,21,True
6943,2013,FEMALE,WHITE NON HISPANIC,SARAH,182,5,True
7089,2013,MALE,HISPANIC,PAUL,12,93,True
7133,2013,FEMALE,BLACK NON HISPANIC,SARAH,34,23,True
7352,2014,MALE,BLACK NON HISPANIC,JACOB,73,15,True
7366,2013,MALE,HISPANIC,JOSEPH,138,19,True
7696,2014,MALE,HISPANIC,DAVID,167,14,True
7894,2014,MALE,HISPANIC,SAUL,16,92,True
7958,2013,FEMALE,HISPANIC,SARAH,44,44,True
8142,2013,MALE,WHITE NON HISPANIC,AARON,81,42,True
8588,2013,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,23,44,True
8831,2013,FEMALE,WHITE NON HISPANIC,MARY,22,70,True
9069,2014,MALE,HISPANIC,ABRAHAM,33,75,True
9102,2014,FEMALE,WHITE NON HISPANIC,MARY,28,68,True
9335,2013,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,42,27,True
9428,2013,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,66,13,True
9494,2013,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,43,26,True
9612,2013,MALE,WHITE NON HISPANIC,DAVID,304,1,True
9709,2013,MALE,WHITE NON HISPANIC,JOSHUA,91,36,True
9716,2013,MALE,BLACK NON HISPANIC,AARON,36,37,True
9725,2013,MALE,BLACK NON HISPANIC,ABRAHAM,10,62,True
9746,2013,MALE,WHITE NON HISPANIC,PAUL,30,80,True
9813,2013,MALE,BLACK NON HISPANIC,JOSEPH,40,35,True
10032,2014,MALE,WHITE NON HISPANIC,PAUL,25,87,True
10048,2013,MALE,BLACK NON HISPANIC,JOSHUA,123,5,True
10202,2013,MALE,BLACK NON HISPANIC,PAUL,14,58,True
10300,2013,MALE,HISPANIC,AARON,122,25,True
10304,2013,MALE,HISPANIC,ABRAHAM,23,82,True
10503,2013,MALE,HISPANIC,DAVID,186,12,True
10698,2013,MALE,HISPANIC,JACOB,297,2,True
10807,2013,MALE,HISPANIC,JOSHUA,145,17,True
10867,2014,MALE,WHITE NON HISPANIC,JACOB,256,5,True
11011,2014,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,32,18,True
11111,2013,MALE,WHITE NON HISPANIC,ABRAHAM,141,20,True
11266,2014,FEMALE,WHITE NON HISPANIC,SARAH,185,7,True
11273,2014,MALE,WHITE NON HISPANIC,ABRAHAM,172,15,True
11544,2014,MALE,BLACK NON HISPANIC,DAVID,46,28,True
11561,2013,MALE,WHITE NON HISPANIC,JACOB,217,8,True
11599,2014,FEMALE,HISPANIC,SARAH,39,47,True
11607,2013,MALE,WHITE NON HISPANIC,JOSEPH,283,2,True
11642,2014,MALE,WHITE NON HISPANIC,SOLOMON,51,63,True
11766,2014,FEMALE,HISPANIC,SALOME,11,72,True
11917,2014,MALE,BLACK NON HISPANIC,JOSHUA,108,7,True
11989,2013,MALE,WHITE NON HISPANIC,SOLOMON,35,75,True
12072,2014,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,18,50,True
12402,2014,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,35,15,True
12686,2014,MALE,WHITE NON HISPANIC,AARON,90,39,True
12713,2018,MALE,HISPANIC,JACOB,241,6,True
12875,2014,MALE,ASIAN AND PACIFIC ISLANDER,AARON,63,14,True
12958,2014,FEMALE,BLACK NON HISPANIC,SARAH,22,29,True
13012,2014,MALE,BLACK NON HISPANIC,AARON,34,38,True
13015,2014,MALE,WHITE NON HISPANIC,JOSHUA,68,49,True
13158,2014,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,48,24,True
13374,2014,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,36,32,True
14412,2014,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,30,38,True
14638,2014,MALE,BLACK NON HISPANIC,JOSEPH,27,45,True
14851,2014,MALE,HISPANIC,JACOB,292,2,True
14887,2014,MALE,HISPANIC,JOSHUA,152,17,True
15093,2014,MALE,WHITE NON HISPANIC,DAVID,272,2,True
15183,2014,MALE,WHITE NON HISPANIC,JOSEPH,300,1,True
15248,2014,MALE,WHITE NON HISPANIC,MOSES,26,86,True
15292,2017,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,32,21,True
16630,2018,MALE,HISPANIC,AARON,143,12,True
23422,2017,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,18,34,True
23633,2017,FEMALE,BLACK NON HISPANIC,SARAH,27,21,True
23755,2018,MALE,HISPANIC,DAVID,129,15,True
23796,2017,FEMALE,HISPANIC,SARAH,58,26,True
24053,2017,FEMALE,WHITE NON HISPANIC,SARAH,190,6,True
24316,2017,FEMALE,WHITE NON HISPANIC,MARY,14,80,True
24460,2017,MALE,ASIAN AND PACIFIC ISLANDER,AARON,47,20,True
24466,2017,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,41,24,True
24491,2017,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,28,36,True
24496,2017,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,27,37,True
24508,2017,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,24,40,True
24622,2017,MALE,BLACK NON HISPANIC,JOSHUA,80,9,True
24626,2017,MALE,BLACK NON HISPANIC,DAVID,66,13,True
24653,2017,MALE,BLACK NON HISPANIC,AARON,38,28,True
24656,2017,MALE,BLACK NON HISPANIC,JACOB,38,28,True
24670,2017,MALE,BLACK NON HISPANIC,JOSEPH,31,34,True
24781,2017,MALE,BLACK NON HISPANIC,SOLOMON,10,55,True
24786,2017,MALE,HISPANIC,JACOB,290,2,True
24794,2017,MALE,HISPANIC,AARON,171,10,True
24802,2017,MALE,HISPANIC,JOSHUA,136,17,True
24803,2017,MALE,HISPANIC,DAVID,132,18,True
24807,2017,MALE,HISPANIC,JOSEPH,120,22,True
24901,2017,MALE,HISPANIC,ABRAHAM,26,73,True
25054,2017,MALE,HISPANIC,SAUL,10,89,True
25059,2017,MALE,WHITE NON HISPANIC,DAVID,282,1,True
25060,2017,MALE,WHITE NON HISPANIC,JOSEPH,279,2,True
25061,2017,MALE,WHITE NON HISPANIC,JACOB,264,3,True
25080,2017,MALE,WHITE NON HISPANIC,ABRAHAM,137,21,True
25119,2017,MALE,WHITE NON HISPANIC,AARON,68,46,True
25123,2017,MALE,WHITE NON HISPANIC,JOSHUA,63,48,True
25140,2017,MALE,WHITE NON HISPANIC,SOLOMON,50,58,True
25234,2017,MALE,WHITE NON HISPANIC,MOSES,23,84,True
25243,2017,MALE,WHITE NON HISPANIC,PAUL,22,85,True
25296,2017,MALE,WHITE NON HISPANIC,SAUL,17,90,True
30155,2016,MALE,HISPANIC,ABRAHAM,42,62,True
30185,2016,FEMALE,WHITE NON HISPANIC,SARAH,202,4,True
30526,2016,MALE,WHITE NON HISPANIC,JOSEPH,261,1,True
30588,2015,FEMALE,WHITE NON HISPANIC,MARY,23,70,True
30648,2016,MALE,WHITE NON HISPANIC,JACOB,236,5,True
30655,2016,MALE,BLACK NON HISPANIC,JOSHUA,94,8,True
30713,2015,MALE,HISPANIC,DAVID,153,16,True
30730,2016,MALE,HISPANIC,JOSEPH,104,26,True
30780,2016,MALE,ASIAN AND PACIFIC ISLANDER,AARON,57,18,True
30806,2015,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,22,43,True
30817,2015,MALE,WHITE NON HISPANIC,DAVID,299,1,True
31015,2015,MALE,HISPANIC,JACOB,293,6,True
31072,2015,MALE,WHITE NON HISPANIC,AARON,73,45,True
31075,2015,MALE,WHITE NON HISPANIC,MOSES,28,76,True
31271,2015,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,37,16,True
31322,2016,MALE,BLACK NON HISPANIC,JOSEPH,26,42,True
31351,2015,FEMALE,BLACK NON HISPANIC,SARAH,30,20,True
31352,2016,MALE,BLACK NON HISPANIC,DAVID,66,13,True
31359,2016,MALE,BLACK NON HISPANIC,AARON,39,29,True
31462,2016,MALE,WHITE NON HISPANIC,DAVID,255,3,True
31507,2015,MALE,HISPANIC,SAUL,15,94,True
31533,2016,MALE,HISPANIC,AARON,141,16,True
31541,2016,MALE,HISPANIC,DAVID,129,21,True
31598,2016,MALE,HISPANIC,PAUL,11,90,True
31622,2016,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,45,26,True
31732,2016,MALE,BLACK NON HISPANIC,ABRAHAM,10,57,True
31841,2015,MALE,BLACK NON HISPANIC,JOSHUA,97,8,True
31913,2015,FEMALE,WHITE NON HISPANIC,SARAH,208,3,True
31933,2016,FEMALE,HISPANIC,SARAH,49,38,True
31988,2015,MALE,HISPANIC,ABRAHAM,36,73,True
32029,2015,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,28,38,True
32030,2016,MALE,HISPANIC,JOSHUA,137,18,True
32107,2016,MALE,WHITE NON HISPANIC,MOSES,37,72,True
32152,2015,MALE,HISPANIC,PAUL,14,95,True
32253,2015,MALE,BLACK NON HISPANIC,DAVID,58,19,True
32262,2015,MALE,WHITE NON HISPANIC,JACOB,236,4,True
32273,2016,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,30,39,True
32319,2016,MALE,BLACK NON HISPANIC,JACOB,57,18,True
32324,2016,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,29,40,True
32371,2015,MALE,HISPANIC,AARON,126,22,True
32421,2015,MALE,WHITE NON HISPANIC,JOSEPH,279,2,True
32434,2015,MALE,BLACK NON HISPANIC,AARON,57,20,True
32441,2016,MALE,WHITE NON HISPANIC,PAUL,31,78,True
32694,2015,MALE,WHITE NON HISPANIC,JOSHUA,81,40,True
32745,2015,MALE,BLACK NON HISPANIC,JACOB,67,14,True
32892,2015,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,35,31,True
33040,2016,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,49,11,True
33139,2016,MALE,WHITE NON HISPANIC,SOLOMON,43,67,True
33177,2015,MALE,HISPANIC,JOSEPH,134,20,True
33197,2016,MALE,WHITE NON HISPANIC,ABRAHAM,163,12,True
33211,2016,FEMALE,BLACK NON HISPANIC,SARAH,25,28,True
33251,2015,MALE,ASIAN AND PACIFIC ISLANDER,AARON,57,17,True
33453,2015,MALE,BLACK NON HISPANIC,JOSEPH,37,37,True
33508,2015,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,46,23,True
33617,2016,MALE,HISPANIC,JACOB,351,2,True
33619,2016,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,26,43,True
33662,2016,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,57,7,True
33706,2016,MALE,WHITE NON HISPANIC,AARON,55,58,True
33784,2016,MALE,WHITE NON HISPANIC,JOSHUA,62,52,True
33886,2015,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,29,24,True
34051,2015,MALE,WHITE NON HISPANIC,ABRAHAM,145,17,True
34063,2015,MALE,WHITE NON HISPANIC,SOLOMON,54,53,True
34079,2016,FEMALE,WHITE NON HISPANIC,MARY,23,71,True
34086,2015,MALE,HISPANIC,JOSHUA,123,24,True
34097,2015,FEMALE,HISPANIC,SARAH,64,32,True
34114,2015,MALE,WHITE NON HISPANIC,PAUL,26,78,True
34174,2015,MALE,WHITE NON HISPANIC,SAUL,10,94,True
37562,2019,MALE,HISPANIC,JACOB,209,6,True
37576,2019,MALE,HISPANIC,DAVID,105,19,True
37578,2019,MALE,HISPANIC,AARON,99,21,True
37581,2019,MALE,HISPANIC,JOSHUA,94,23,True
37590,2019,MALE,HISPANIC,JOSEPH,78,30,True
37681,2019,MALE,HISPANIC,ABRAHAM,23,70,True
37730,2019,MALE,HISPANIC,SAUL,17,76,True
37873,2019,FEMALE,HISPANIC,SARAH,39,39,True
38098,2019,MALE,ASIAN AND PACIFIC ISLANDER,AARON,45,22,True
38115,2019,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,31,33,True
38137,2019,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,22,41,True
38145,2019,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,21,42,True
38170,2019,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,16,47,True
38267,2019,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,38,13,True
38292,2019,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,23,22,True
38407,2019,MALE,WHITE NON HISPANIC,DAVID,252,1,True
38408,2019,MALE,WHITE NON HISPANIC,JOSEPH,233,2,True
38411,2019,MALE,WHITE NON HISPANIC,JACOB,213,4,True
38426,2019,MALE,WHITE NON HISPANIC,ABRAHAM,141,18,True
38465,2019,MALE,WHITE NON HISPANIC,AARON,66,48,True
38482,2019,MALE,WHITE NON HISPANIC,SOLOMON,48,59,True
38492,2019,MALE,WHITE NON HISPANIC,JOSHUA,45,62,True
38620,2019,MALE,WHITE NON HISPANIC,MOSES,19,88,True
38621,2019,MALE,WHITE NON HISPANIC,PAUL,19,88,True
38776,2019,FEMALE,WHITE NON HISPANIC,SARAH,168,8,True
38996,2019,FEMALE,WHITE NON HISPANIC,MARY,17,77,True
39167,2019,MALE,BLACK NON HISPANIC,JOSHUA,53,15,True
39184,2019,MALE,BLACK NON HISPANIC,DAVID,39,24,True
39189,2019,MALE,BLACK NON HISPANIC,AARON,34,27,True
39200,2019,MALE,BLACK NON HISPANIC,JACOB,29,32,True
39268,2019,MALE,BLACK NON HISPANIC,JOSEPH,14,47,True
39423,2019,FEMALE,BLACK NON HISPANIC,SARAH,15,29,True
47570,2018,MALE,HISPANIC,JOSHUA,100,24,True
47575,2018,MALE,HISPANIC,JOSEPH,92,28,True
47680,2018,MALE,HISPANIC,ABRAHAM,23,76,True
47856,2018,FEMALE,HISPANIC,SARAH,51,31,True
48098,2018,MALE,ASIAN AND PACIFIC ISLANDER,AARON,58,13,True
48107,2018,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,46,19,True
48123,2018,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,34,29,True
48162,2018,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,19,42,True
48204,2018,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,15,46,True
48278,2018,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,35,17,True
48279,2018,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,35,17,True
48422,2018,MALE,WHITE NON HISPANIC,DAVID,274,1,True
48423,2018,MALE,WHITE NON HISPANIC,JOSEPH,248,2,True
48426,2018,MALE,WHITE NON HISPANIC,JACOB,217,5,True
48445,2018,MALE,WHITE NON HISPANIC,ABRAHAM,126,23,True
48473,2018,MALE,WHITE NON HISPANIC,AARON,76,44,True
48480,2018,MALE,WHITE NON HISPANIC,JOSHUA,69,48,True
48547,2018,MALE,WHITE NON HISPANIC,SOLOMON,31,80,True
48561,2018,MALE,WHITE NON HISPANIC,MOSES,28,83,True
48575,2018,MALE,WHITE NON HISPANIC,PAUL,26,85,True
48789,2018,FEMALE,WHITE NON HISPANIC,SARAH,214,3,True
48985,2018,FEMALE,WHITE NON HISPANIC,MARY,20,75,True
49154,2018,FEMALE,WHITE NON HISPANIC,JOANNA,10,85,True
49183,2018,MALE,BLACK NON HISPANIC,JOSHUA,72,10,True
49206,2018,MALE,BLACK NON HISPANIC,DAVID,37,25,True
49208,2018,MALE,BLACK NON HISPANIC,JACOB,36,26,True
49236,2018,MALE,BLACK NON HISPANIC,AARON,27,35,True
49249,2018,MALE,BLACK NON HISPANIC,JOSEPH,21,40,True
49374,2018,FEMALE,BLACK NON HISPANIC,SARAH,28,22,True
57584,2020,MALE,HISPANIC,JACOB,227,3,True
57599,2020,MALE,HISPANIC,JOSEPH,99,17,True
57600,2020,MALE,HISPANIC,AARON,98,18,True
57606,2020,MALE,HISPANIC,DAVID,84,22,True
57615,2020,MALE,HISPANIC,JOSHUA,67,29,True
57737,2020,MALE,HISPANIC,ABRAHAM,17,71,True
57841,2020,MALE,HISPANIC,PAUL,10,78,True
57880,2020,FEMALE,HISPANIC,SARAH,45,30,True
58095,2020,MALE,ASIAN AND PACIFIC ISLANDER,AARON,46,10,True
58128,2020,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,24,28,True
58160,2020,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,17,35,True
58171,2020,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,15,37,True
58195,2020,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,12,40,True
58247,2020,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,32,15,True
58282,2020,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,18,28,True
58358,2020,MALE,WHITE NON HISPANIC,JOSEPH,232,1,True
58359,2020,MALE,WHITE NON HISPANIC,DAVID,230,2,True
58362,2020,MALE,WHITE NON HISPANIC,JACOB,176,5,True
58368,2020,MALE,WHITE NON HISPANIC,ABRAHAM,151,11,True
58412,2020,MALE,WHITE NON HISPANIC,AARON,62,44,True
58438,2020,MALE,WHITE NON HISPANIC,SOLOMON,43,58,True
58447,2020,MALE,WHITE NON HISPANIC,JOSHUA,37,63,True
58542,2020,MALE,WHITE NON HISPANIC,PAUL,21,78,True
58575,2020,MALE,WHITE NON HISPANIC,MOSES,17,82,True
58690,2020,FEMALE,WHITE NON HISPANIC,SARAH,189,3,True
58846,2020,FEMALE,WHITE NON HISPANIC,MARY,21,70,True
59062,2020,MALE,BLACK NON HISPANIC,JOSHUA,47,14,True
59078,2020,MALE,BLACK NON HISPANIC,JACOB,34,23,True
59093,2020,MALE,BLACK NON HISPANIC,AARON,28,28,True
59120,2020,MALE,BLACK NON HISPANIC,JOSEPH,18,38,True
59121,2020,MALE,BLACK NON HISPANIC,DAVID,17,39,True
59198,2020,MALE,BLACK NON HISPANIC,SOLOMON,10,46,True
59332,2020,FEMALE,BLACK NON HISPANIC,SARAH,11,32,True
59357,2021,MALE,HISPANIC,JACOB,161,6,True
59368,2021,MALE,HISPANIC,AARON,94,16,True
59377,2021,MALE,HISPANIC,JOSHUA,76,23,True
59381,2021,MALE,HISPANIC,JOSEPH,73,25,True
59386,2021,MALE,HISPANIC,DAVID,63,28,True
59456,2021,MALE,HISPANIC,ABRAHAM,25,60,True
59676,2021,FEMALE,HISPANIC,SARAH,34,40,True
59893,2021,MALE,ASIAN AND PACIFIC ISLANDER,AARON,44,10,True
59908,2021,MALE,ASIAN AND PACIFIC ISLANDER,JACOB,30,19,True
59957,2021,MALE,ASIAN AND PACIFIC ISLANDER,JOSEPH,15,32,True
59985,2021,MALE,ASIAN AND PACIFIC ISLANDER,DAVID,12,35,True
59999,2021,MALE,ASIAN AND PACIFIC ISLANDER,JOSHUA,11,36,True
60047,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,SARAH,24,19,True
60104,2021,FEMALE,ASIAN AND PACIFIC ISLANDER,JOANNA,11,31,True
60134,2021,MALE,WHITE NON HISPANIC,DAVID,221,2,True
60135,2021,MALE,WHITE NON HISPANIC,JOSEPH,219,3,True
60140,2021,MALE,WHITE NON HISPANIC,JACOB,168,8,True
60144,2021,MALE,WHITE NON HISPANIC,ABRAHAM,144,12,True
60181,2021,MALE,WHITE NON HISPANIC,AARON,66,40,True
60224,2021,MALE,WHITE NON HISPANIC,SOLOMON,37,64,True
60229,2021,MALE,WHITE NON HISPANIC,JOSHUA,36,65,True
60317,2021,MALE,WHITE NON HISPANIC,MOSES,20,81,True
60345,2021,MALE,WHITE NON HISPANIC,PAUL,17,84,True
60478,2021,MALE,WHITE NON HISPANIC,SAUL,10,91,True
60493,2021,FEMALE,WHITE NON HISPANIC,SARAH,160,8,True
60788,2021,FEMALE,WHITE NON HISPANIC,MARY,12,78,True
60842,2021,FEMALE,WHITE NON HISPANIC,MARA,10,80,True
60870,2021,MALE,BLACK NON HISPANIC,JOSHUA,40,16,True
60899,2021,MALE,BLACK NON HISPANIC,DAVID,25,30,True
60910,2021,MALE,BLACK NON HISPANIC,AARON,21,34,True
60912,2021,MALE,BLACK NON HISPANIC,JACOB,21,34,True
60947,2021,MALE,BLACK NON HISPANIC,JOSEPH,14,41,True
61122,2021,FEMALE,BLACK NON HISPANIC,SARAH,11,30,True

In [60]:
true_count_2015 = data.loc[data['is_Biblical'] & (data['Ethnicity'] == 'BLACK NON HISPANIC'),'Count'].sum()
true_count_2015

3184

In [58]:
true_count_2012 = data.loc[data['is_Biblical'] & (data['Year of Birth'] == 2012),'Count']
pd.set_option('display.max_rows', None)
true_count_2012

4048     37
4101     47
4276     29
4565     10
4569     43
4789     11
4857     23
4925    209
4979     66
5030     40
5061     48
5077     29
5078     45
5158     59
5212     67
5235     58
5254     52
5255    124
5313     13
5340    126
5343     19
5413    176
5475    293
5511    150
5512    177
5582     12
5604     12
5630     95
5631    132
5704    289
5776    242
5791    300
5792     79
5849     18
5872     28
5920     36
Name: Count, dtype: int64